version: '3.8'

services:

  # 🔋 Charge Request Service
  charge_request:
    build: ./charge_request_service
    ports:
      - "5001:5001"
    depends_on:
      - load_balancer

  # ⚖️ Load Balancer
  load_balancer:
    build: ./load_balancer
    ports:
      - "5002:5002"
    depends_on:
      - substation1
      - substation2
      - substation3

  # ⚡ Substations (3 replicas)
  substation1:
    build: ./substation_service
    ports:
      - "5003:5003"  # expose one for Prometheus
    environment:
      - INSTANCE_ID=1

  substation2:
    build: ./substation_service
    environment:
      - INSTANCE_ID=2

  substation3:
    build: ./substation_service
    environment:
      - INSTANCE_ID=3

  #  Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  #  Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus